/**:
  ros__parameters:
    x0: 0.0
    y0: 0.0
    theta0: 1.28
    arena_x_length: 10.0
    arena_y_length: 5.0
    obstacles/x: [-0.5,0.8,0.4,-0.6]
    obstacles/y: [-0.7,-0.8,0.8,0.65]
    obstacles/r: [0.05,0.05,0.05,0.05]